### ISSUE TITLE
Discuss future direction of the test-dev-cluster

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/test-dev-cluster#35]
The test-dev-cluster in its current incarnation has a few critical issues that we should discuss and decide how we want to tackle these / if this requires a fundamental redesign of the test-dev-cluster.

I am currently aware of the following issues (and raise no claim whatsoever about the completeness of this list):

- Issue with newer systemd versions (or more specifically cgroups I believe) - @siegfriedweber figured out how to fix that I think
- Doesn't work with encrypted disks
- Since switching do docker compose it is not possible to run multiple oses in parallel, a teardown and restart of the entire environment in between tests is required

**Comment by siegfriedweber** [comment]
The unified cgroup hierarchy (cgroupsv2) can be disabled with the kernel parameter `systemd.unified_cgroup_hierarchy=0`.

**Comment by lfrancke** [comment]
The follow-up tickets for this are https://github.com/stackabletech/integration-tests/issues/18 as well as a reworked documentation that explains how to get started using kind.
